/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personalassistant;

import java.awt.Toolkit;

/**
 *
 * @author Filipe
 */
public class NewJFrameGUI extends javax.swing.JFrame {
    
    private float xsize;
    private float ysize;
    
    private PersonalAssistant market;
    /**
     * Creates new form NewJFrameGUI
     */
    public NewJFrameGUI() {

        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.xsize = xsize;
        this.ysize = ysize;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Generators = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Retailers = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_TradingCoordination = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList_LargeConsumers = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList_MediumSmallConsumers = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList_TranCos_DistCos = new javax.swing.JList<>();
        jScrollPane_webtext = new javax.swing.JScrollPane();
        jTextArea_webtext = new javax.swing.JTextArea();
        jLabel_clock = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_Agents = new javax.swing.JMenu();
        jMenu_Agents_New = new javax.swing.JMenu();
        jMenuItem_Agents_New_GenCos = new javax.swing.JMenuItem();
        jMenuItem_Agents_New_RetailCos = new javax.swing.JMenuItem();
        jMenuItem_Agents_New_TransCos = new javax.swing.JMenuItem();
        jMenuItem_Agents_New_DistCos = new javax.swing.JMenuItem();
        jMenuItem_Agents_New_Consumers = new javax.swing.JMenuItem();
        jMenu_Agents_Load = new javax.swing.JMenu();
        jMenuItem_Load_GenCos = new javax.swing.JMenuItem();
        jMenuItem_Load_RetailCos = new javax.swing.JMenuItem();
        jMenuItem_Load_TransCos = new javax.swing.JMenuItem();
        jMenuItem_Load_DistCos = new javax.swing.JMenuItem();
        jMenuItem_Load_Consumers = new javax.swing.JMenuItem();
        jMenuItem_Load_Coalitiona = new javax.swing.JMenuItem();
        jMenuItem_Agents_Save = new javax.swing.JMenuItem();
        jMenuItem_Agents_Kill = new javax.swing.JMenuItem();
        jMenu_Markets = new javax.swing.JMenu();
        jMenu_Markets_EnergyMarket = new javax.swing.JMenu();
        jMenuItem_Markets_EnergyMarkets_DayAheadMarket = new javax.swing.JMenuItem();
        jMenuItem_Markets_EnergyMarkets_IntradayMarket = new javax.swing.JMenuItem();
        jMenuItem_Markets_EnergyMarkets_RealTimeMarket = new javax.swing.JMenuItem();
        jMenu_Markets_OverTheCounterContracts = new javax.swing.JMenu();
        jMenu_Markets_OverTheCounterContracts_OTC = new javax.swing.JMenuItem();
        jMenuItem_Markets_AncillaryServicesMarket = new javax.swing.JMenuItem();
        jMenuItem_Markets_TransmissionRightsMarket = new javax.swing.JMenuItem();
        jMenuItem_Markets_CapacityMarket = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Markets_ForwardMarket = new javax.swing.JMenuItem();
        jMenuItem_Markets_FuturesMarket = new javax.swing.JMenuItem();
        jMenuItem_Markets_OptionsMarket = new javax.swing.JMenuItem();
        jMenu_Participants = new javax.swing.JMenu();
        jMenuItem_Participants_Generators = new javax.swing.JMenuItem();
        jMenuItem_Participants_Retailers = new javax.swing.JMenuItem();
        jMenu_Participants_PoolTrading = new javax.swing.JMenu();
        jMenuItem_Participants_PoolTrading_Generators = new javax.swing.JMenuItem();
        jMenuItem_Participants_PoolTrading_Retailers = new javax.swing.JMenuItem();
        jMenu_Participants_PoolTrading_CaseStudies = new javax.swing.JMenu();
        jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy1 = new javax.swing.JMenuItem();
        jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy2 = new javax.swing.JMenuItem();
        jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy3 = new javax.swing.JMenuItem();
        jMenu_Participants_OTCTrading = new javax.swing.JMenu();
        jMenuItem_Participants_OTCTrading_Generators = new javax.swing.JMenuItem();
        jMenuItem_Participants_OTCTrading_Retailers = new javax.swing.JMenuItem();
        jMenu_Participants_BilateralTrading = new javax.swing.JMenu();
        jMenu_Participants_BilateralTrading_AlteratingOffers = new javax.swing.JMenu();
        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Generators = new javax.swing.JMenuItem();
        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Retailers = new javax.swing.JMenuItem();
        jMenuItem_Participants_BilateralTrading_AlteratingOffers_LargeConsumers = new javax.swing.JMenuItem();
        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Consumers = new javax.swing.JMenuItem();
        jMenuItem_Participants_BilateralTrading_ContractNet = new javax.swing.JMenuItem();
        jMenu_Simulation = new javax.swing.JMenu();
        jMenu_Simulation_Wholesale = new javax.swing.JMenu();
        jMenu_Simulation_Wholesale_Start = new javax.swing.JMenu();
        jMenu_Simulation_Wholesale_Start_SMP = new javax.swing.JMenu();
        jMenuItem_Simulation_Wholesale_Start_SMP_Symmetrical = new javax.swing.JMenuItem();
        jMenuItem_Simulation_Wholesale_Start_SMP_Asymmetrical = new javax.swing.JMenuItem();
        jMenuItem_Simulation_Wholesale_Start_LMP = new javax.swing.JMenuItem();
        jMenuItem_Simulation_Wholesale_Pause = new javax.swing.JMenuItem();
        jMenuItem_Simulation_Wholesale_Stop = new javax.swing.JMenuItem();
        jMenu_Simulation_Bilateral = new javax.swing.JMenu();
        jMenuItem_Simulation_Bilateral_Start = new javax.swing.JMenuItem();
        jMenuItem_Simulation_Bilateral_Pause = new javax.swing.JMenuItem();
        jMenuItem_Simulation_Bilateral_Stop = new javax.swing.JMenuItem();
        jMenuItem_Simulation_OTC = new javax.swing.JMenuItem();
        jMenuItem_Simulation_CaseStudy = new javax.swing.JMenuItem();
        jMenuItem_Simulation_CaseStudyNoWind = new javax.swing.JMenuItem();
        jMenu_Preferences = new javax.swing.JMenu();
        jMenu_Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multi-agent plataform");
        setBackground(new java.awt.Color(153, 153, 153));

        jSplitPane1.setDividerLocation(-2);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setAlignmentX(xsize-xsize/4);
        jSplitPane1.setAlignmentY(ysize);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSplitPane1.setBottomComponent(jScrollPane1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/761m3.jpg"))); // NOI18N
        jSplitPane1.setTopComponent(jLabel1);

        jTextPane1.setText("  Hora:      01h      02h       03h       04h      05h       06h       07h      08h       09h      10h       11h      12h       13h      14h       15h       16h       17h      18h       19h       20h      21h       22h       23h      24h\n Preço:   00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00 | 00.00\n");
        jScrollPane8.setViewportView(jTextPane1);

        jSplitPane1.setRightComponent(jScrollPane8);

        jList_Generators.setBackground(new java.awt.Color(231, 231, 231));
        jList_Generators.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Generators (GenCos)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jScrollPane2.setViewportView(jList_Generators);

        jList_Retailers.setBackground(new java.awt.Color(231, 231, 231));
        jList_Retailers.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Retailers (RetailCos)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jScrollPane3.setViewportView(jList_Retailers);

        jList_TradingCoordination.setBackground(new java.awt.Color(245, 245, 245));
        jList_TradingCoordination.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Trading Coordination", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jList_TradingCoordination.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jList_TradingCoordination.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Market Operator", "Personal Assistant" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList_TradingCoordination);

        jList_LargeConsumers.setBackground(new java.awt.Color(231, 231, 231));
        jList_LargeConsumers.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Large Consumers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jScrollPane5.setViewportView(jList_LargeConsumers);

        jList_MediumSmallConsumers.setBackground(new java.awt.Color(231, 231, 231));
        jList_MediumSmallConsumers.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Medium/Small Consumers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jScrollPane6.setViewportView(jList_MediumSmallConsumers);

        jList_TranCos_DistCos.setBackground(new java.awt.Color(245, 245, 245));
        jList_TranCos_DistCos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "TransCos & DistCos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jScrollPane7.setViewportView(jList_TranCos_DistCos);

        jTextArea_webtext.setEditable(false);
        jTextArea_webtext.setColumns(20);
        jTextArea_webtext.setRows(5);
        jTextArea_webtext.setText("    Preço marginal no sistema eléctrico Português (EUR/MWh):\n  01h - b  /  02h - b  /  03h - b  /  04h - b  /  05h - b  /  06h - b  /  07h - b  /  08h - b  /  09h - b  /  10h - b  /  11h - b  /  12h - b  /  13h - b  /  14h - b  /  15h - b  /  16h - b  /  17h - b  /  18h - b  /  19h - b  /  20h - b  /  21h - b  /  22h - b  /  23h - b  /  24h - b\n\n\n\n\n\n  ||   01h  ||    2h    ||   3h    ||   4 h   ||    5h    ||    6h   ||   7h    ||    8h    ||   9h    ||   10h  ||   11h   ||   12h  ||   13h  ||   14h  ||    15h  ||  16h   ||   17h  ||   18h   ||   19h  ||   20h  ||   21h   ||   22h  ||   23h  ||   24h   ||\n  || 59.58 || 55.59 || 49.01 || 46.51 || 45.01 || 44.01 || 44.51 || 44.08 || 44.44 || 45.75 || 53.68 || 56.01 || 59.58 || 55.59 || 49.01 || 46.51 || 45.01 || 44.01 || 44.51 || 44.08 || 44.44 || 45.75 || 53.68 || 56.01 ||");
        jTextArea_webtext.setToolTipText("");
        jScrollPane_webtext.setViewportView(jTextArea_webtext);

        jLabel_clock.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_clock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/clock.png"))); // NOI18N
        jLabel_clock.setText("jLabel2");

        jScrollPane9.setViewportView(jTextPane2);

        jMenu_Agents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/user-52m.png"))); // NOI18N
        jMenu_Agents.setText("Agents");

        jMenu_Agents_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenu_Agents_New.setText("New");

        jMenuItem_Agents_New_GenCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/producers_black.png"))); // NOI18N
        jMenuItem_Agents_New_GenCos.setText("Generators (GenCos)");
        jMenu_Agents_New.add(jMenuItem_Agents_New_GenCos);

        jMenuItem_Agents_New_RetailCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/retailers_black.png"))); // NOI18N
        jMenuItem_Agents_New_RetailCos.setText("Retailers (RetailCos)");
        jMenu_Agents_New.add(jMenuItem_Agents_New_RetailCos);

        jMenuItem_Agents_New_TransCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Agents_New_TransCos.setText("Transmission Companies (TransCos)");
        jMenuItem_Agents_New_TransCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Agents_New_TransCosActionPerformed(evt);
            }
        });
        jMenu_Agents_New.add(jMenuItem_Agents_New_TransCos);

        jMenuItem_Agents_New_DistCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Agents_New_DistCos.setText("Distribution Companies (DistCos)");
        jMenu_Agents_New.add(jMenuItem_Agents_New_DistCos);

        jMenuItem_Agents_New_Consumers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Agents_New_Consumers.setText("Consumers");
        jMenu_Agents_New.add(jMenuItem_Agents_New_Consumers);

        jMenu_Agents.add(jMenu_Agents_New);

        jMenu_Agents_Load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/load.jpg"))); // NOI18N
        jMenu_Agents_Load.setText("Load");

        jMenuItem_Load_GenCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/producers_black.png"))); // NOI18N
        jMenuItem_Load_GenCos.setText("Generators (GenCos)");
        jMenu_Agents_Load.add(jMenuItem_Load_GenCos);

        jMenuItem_Load_RetailCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/retailers_black.png"))); // NOI18N
        jMenuItem_Load_RetailCos.setText("Retailers (RetailCos)");
        jMenu_Agents_Load.add(jMenuItem_Load_RetailCos);

        jMenuItem_Load_TransCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Load_TransCos.setText("Transmission Companies (TransCos)");
        jMenu_Agents_Load.add(jMenuItem_Load_TransCos);

        jMenuItem_Load_DistCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Load_DistCos.setText("Distribution Companies (DistCos)");
        jMenu_Agents_Load.add(jMenuItem_Load_DistCos);

        jMenuItem_Load_Consumers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Load_Consumers.setText("Consumers");
        jMenu_Agents_Load.add(jMenuItem_Load_Consumers);

        jMenuItem_Load_Coalitiona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/new2.jpg"))); // NOI18N
        jMenuItem_Load_Coalitiona.setText("Coalitions");
        jMenu_Agents_Load.add(jMenuItem_Load_Coalitiona);

        jMenu_Agents.add(jMenu_Agents_Load);

        jMenuItem_Agents_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/save.jpg"))); // NOI18N
        jMenuItem_Agents_Save.setText("Save");
        jMenu_Agents.add(jMenuItem_Agents_Save);

        jMenuItem_Agents_Kill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/kill.jpg"))); // NOI18N
        jMenuItem_Agents_Kill.setText("Kill");
        jMenu_Agents.add(jMenuItem_Agents_Kill);

        jMenuBar.add(jMenu_Agents);

        jMenu_Markets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/graph-1.png"))); // NOI18N
        jMenu_Markets.setText("Markets");

        jMenu_Markets_EnergyMarket.setText("Energy Market");

        jMenuItem_Markets_EnergyMarkets_DayAheadMarket.setText("Day-ahead Market");
        jMenu_Markets_EnergyMarket.add(jMenuItem_Markets_EnergyMarkets_DayAheadMarket);

        jMenuItem_Markets_EnergyMarkets_IntradayMarket.setText("Intraday Market");
        jMenu_Markets_EnergyMarket.add(jMenuItem_Markets_EnergyMarkets_IntradayMarket);

        jMenuItem_Markets_EnergyMarkets_RealTimeMarket.setText("Real-time Market");
        jMenu_Markets_EnergyMarket.add(jMenuItem_Markets_EnergyMarkets_RealTimeMarket);

        jMenu_Markets.add(jMenu_Markets_EnergyMarket);

        jMenu_Markets_OverTheCounterContracts.setText("Over-the-Counter Contracts");

        jMenu_Markets_OverTheCounterContracts_OTC.setText("OTC");
        jMenu_Markets_OverTheCounterContracts.add(jMenu_Markets_OverTheCounterContracts_OTC);

        jMenu_Markets.add(jMenu_Markets_OverTheCounterContracts);

        jMenuItem_Markets_AncillaryServicesMarket.setText("Ancillary-Services Market");
        jMenu_Markets.add(jMenuItem_Markets_AncillaryServicesMarket);

        jMenuItem_Markets_TransmissionRightsMarket.setText("Transmission-Rights Market");
        jMenuItem_Markets_TransmissionRightsMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Markets_TransmissionRightsMarketActionPerformed(evt);
            }
        });
        jMenu_Markets.add(jMenuItem_Markets_TransmissionRightsMarket);

        jMenuItem_Markets_CapacityMarket.setText("Capacity Market");
        jMenu_Markets.add(jMenuItem_Markets_CapacityMarket);
        jMenu_Markets.add(jSeparator1);

        jMenuItem_Markets_ForwardMarket.setText("Forward Market");
        jMenu_Markets.add(jMenuItem_Markets_ForwardMarket);

        jMenuItem_Markets_FuturesMarket.setText("Futures Market");
        jMenu_Markets.add(jMenuItem_Markets_FuturesMarket);

        jMenuItem_Markets_OptionsMarket.setText("Options Market");
        jMenu_Markets.add(jMenuItem_Markets_OptionsMarket);

        jMenuBar.add(jMenu_Markets);

        jMenu_Participants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/collaboration.png"))); // NOI18N
        jMenu_Participants.setText("Participants");

        jMenuItem_Participants_Generators.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/producers_black.png"))); // NOI18N
        jMenuItem_Participants_Generators.setText("Generators");
        jMenu_Participants.add(jMenuItem_Participants_Generators);

        jMenuItem_Participants_Retailers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/retailers_black.png"))); // NOI18N
        jMenuItem_Participants_Retailers.setText("Retailers");
        jMenu_Participants.add(jMenuItem_Participants_Retailers);

        jMenu_Participants_PoolTrading.setText("Pool Trading");

        jMenuItem_Participants_PoolTrading_Generators.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/producers_black.png"))); // NOI18N
        jMenuItem_Participants_PoolTrading_Generators.setText("Generators");
        jMenu_Participants_PoolTrading.add(jMenuItem_Participants_PoolTrading_Generators);

        jMenuItem_Participants_PoolTrading_Retailers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/retailers_black.png"))); // NOI18N
        jMenuItem_Participants_PoolTrading_Retailers.setText("Retailers");
        jMenu_Participants_PoolTrading.add(jMenuItem_Participants_PoolTrading_Retailers);

        jMenu_Participants_PoolTrading_CaseStudies.setText("Case Studies");

        jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy1.setText("Case Study 1");
        jMenu_Participants_PoolTrading_CaseStudies.add(jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy1);

        jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy2.setText("Case Study 2");
        jMenu_Participants_PoolTrading_CaseStudies.add(jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy2);

        jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy3.setText("Case Study 3");
        jMenu_Participants_PoolTrading_CaseStudies.add(jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy3);

        jMenu_Participants_PoolTrading.add(jMenu_Participants_PoolTrading_CaseStudies);

        jMenu_Participants.add(jMenu_Participants_PoolTrading);

        jMenu_Participants_OTCTrading.setText("OTC Trading");

        jMenuItem_Participants_OTCTrading_Generators.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/producers_black.png"))); // NOI18N
        jMenuItem_Participants_OTCTrading_Generators.setText("Generators");
        jMenu_Participants_OTCTrading.add(jMenuItem_Participants_OTCTrading_Generators);

        jMenuItem_Participants_OTCTrading_Retailers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/retailers_black.png"))); // NOI18N
        jMenuItem_Participants_OTCTrading_Retailers.setText("Retailers");
        jMenu_Participants_OTCTrading.add(jMenuItem_Participants_OTCTrading_Retailers);

        jMenu_Participants.add(jMenu_Participants_OTCTrading);

        jMenu_Participants_BilateralTrading.setText("Bilateral Trading");

        jMenu_Participants_BilateralTrading_AlteratingOffers.setText("Alteranting Offers");

        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Generators.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/producers_black.png"))); // NOI18N
        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Generators.setText("Generators");
        jMenu_Participants_BilateralTrading_AlteratingOffers.add(jMenuItem_Participants_BilateralTrading_AlteratingOffers_Generators);

        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Retailers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/retailers_black.png"))); // NOI18N
        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Retailers.setText("Retailers");
        jMenu_Participants_BilateralTrading_AlteratingOffers.add(jMenuItem_Participants_BilateralTrading_AlteratingOffers_Retailers);

        jMenuItem_Participants_BilateralTrading_AlteratingOffers_LargeConsumers.setText("Large Consumers");
        jMenu_Participants_BilateralTrading_AlteratingOffers.add(jMenuItem_Participants_BilateralTrading_AlteratingOffers_LargeConsumers);

        jMenuItem_Participants_BilateralTrading_AlteratingOffers_Consumers.setText("Consumers");
        jMenu_Participants_BilateralTrading_AlteratingOffers.add(jMenuItem_Participants_BilateralTrading_AlteratingOffers_Consumers);

        jMenu_Participants_BilateralTrading.add(jMenu_Participants_BilateralTrading_AlteratingOffers);

        jMenuItem_Participants_BilateralTrading_ContractNet.setText("Contract Net");
        jMenu_Participants_BilateralTrading.add(jMenuItem_Participants_BilateralTrading_ContractNet);

        jMenu_Participants.add(jMenu_Participants_BilateralTrading);

        jMenuBar.add(jMenu_Participants);

        jMenu_Simulation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/pie-chart.png"))); // NOI18N
        jMenu_Simulation.setText("Simulation");

        jMenu_Simulation_Wholesale.setText("Wholesale");

        jMenu_Simulation_Wholesale_Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/start.png"))); // NOI18N
        jMenu_Simulation_Wholesale_Start.setText("Start");

        jMenu_Simulation_Wholesale_Start_SMP.setText("SMP");

        jMenuItem_Simulation_Wholesale_Start_SMP_Symmetrical.setText("Symmetrical");
        jMenu_Simulation_Wholesale_Start_SMP.add(jMenuItem_Simulation_Wholesale_Start_SMP_Symmetrical);

        jMenuItem_Simulation_Wholesale_Start_SMP_Asymmetrical.setText("Asymmetrical");
        jMenu_Simulation_Wholesale_Start_SMP.add(jMenuItem_Simulation_Wholesale_Start_SMP_Asymmetrical);

        jMenu_Simulation_Wholesale_Start.add(jMenu_Simulation_Wholesale_Start_SMP);

        jMenuItem_Simulation_Wholesale_Start_LMP.setText("LMP");
        jMenu_Simulation_Wholesale_Start.add(jMenuItem_Simulation_Wholesale_Start_LMP);

        jMenu_Simulation_Wholesale.add(jMenu_Simulation_Wholesale_Start);

        jMenuItem_Simulation_Wholesale_Pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/pause.png"))); // NOI18N
        jMenuItem_Simulation_Wholesale_Pause.setText("Pause");
        jMenu_Simulation_Wholesale.add(jMenuItem_Simulation_Wholesale_Pause);

        jMenuItem_Simulation_Wholesale_Stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/stop_black.png"))); // NOI18N
        jMenuItem_Simulation_Wholesale_Stop.setText("Stop");
        jMenu_Simulation_Wholesale.add(jMenuItem_Simulation_Wholesale_Stop);

        jMenu_Simulation.add(jMenu_Simulation_Wholesale);

        jMenu_Simulation_Bilateral.setText("Bilateral");

        jMenuItem_Simulation_Bilateral_Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/start.png"))); // NOI18N
        jMenuItem_Simulation_Bilateral_Start.setText("Start");
        jMenu_Simulation_Bilateral.add(jMenuItem_Simulation_Bilateral_Start);

        jMenuItem_Simulation_Bilateral_Pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/pause.png"))); // NOI18N
        jMenuItem_Simulation_Bilateral_Pause.setText("Pause");
        jMenu_Simulation_Bilateral.add(jMenuItem_Simulation_Bilateral_Pause);

        jMenuItem_Simulation_Bilateral_Stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/stop_black.png"))); // NOI18N
        jMenuItem_Simulation_Bilateral_Stop.setText("Stop");
        jMenu_Simulation_Bilateral.add(jMenuItem_Simulation_Bilateral_Stop);

        jMenu_Simulation.add(jMenu_Simulation_Bilateral);

        jMenuItem_Simulation_OTC.setText("OTC");
        jMenu_Simulation.add(jMenuItem_Simulation_OTC);

        jMenuItem_Simulation_CaseStudy.setText("Case Study");
        jMenu_Simulation.add(jMenuItem_Simulation_CaseStudy);

        jMenuItem_Simulation_CaseStudyNoWind.setText("Case Study no Wind");
        jMenu_Simulation.add(jMenuItem_Simulation_CaseStudyNoWind);

        jMenuBar.add(jMenu_Simulation);

        jMenu_Preferences.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/tool.jpg"))); // NOI18N
        jMenu_Preferences.setText("Preferences");
        jMenu_Preferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_PreferencesMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu_Preferences);

        jMenu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalassistant/images/exit2.png"))); // NOI18N
        jMenu_Exit.setText("Exit");
        jMenu_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ExitMouseClicked(evt);
            }
        });
        jMenu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ExitActionPerformed(evt);
            }
        });
        jMenuBar.add(jMenu_Exit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane_webtext, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_clock, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addComponent(jScrollPane9))
                                .addGap(8, 8, 8)))))
                .addContainerGap(625, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_clock, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_webtext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Agents_New_TransCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Agents_New_TransCosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Agents_New_TransCosActionPerformed

    private void jMenuItem_Markets_TransmissionRightsMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Markets_TransmissionRightsMarketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Markets_TransmissionRightsMarketActionPerformed

    private void jMenu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_ExitActionPerformed

    private void jMenu_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu_ExitMouseClicked

    private void jMenu_PreferencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_PreferencesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_PreferencesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_clock;
    private javax.swing.JList<String> jList_Generators;
    private javax.swing.JList<String> jList_LargeConsumers;
    private javax.swing.JList<String> jList_MediumSmallConsumers;
    private javax.swing.JList<String> jList_Retailers;
    private javax.swing.JList<String> jList_TradingCoordination;
    private javax.swing.JList<String> jList_TranCos_DistCos;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem_Agents_Kill;
    private javax.swing.JMenuItem jMenuItem_Agents_New_Consumers;
    private javax.swing.JMenuItem jMenuItem_Agents_New_DistCos;
    private javax.swing.JMenuItem jMenuItem_Agents_New_GenCos;
    private javax.swing.JMenuItem jMenuItem_Agents_New_RetailCos;
    private javax.swing.JMenuItem jMenuItem_Agents_New_TransCos;
    private javax.swing.JMenuItem jMenuItem_Agents_Save;
    private javax.swing.JMenuItem jMenuItem_Load_Coalitiona;
    private javax.swing.JMenuItem jMenuItem_Load_Consumers;
    private javax.swing.JMenuItem jMenuItem_Load_DistCos;
    private javax.swing.JMenuItem jMenuItem_Load_GenCos;
    private javax.swing.JMenuItem jMenuItem_Load_RetailCos;
    private javax.swing.JMenuItem jMenuItem_Load_TransCos;
    private javax.swing.JMenuItem jMenuItem_Markets_AncillaryServicesMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_CapacityMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_EnergyMarkets_DayAheadMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_EnergyMarkets_IntradayMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_EnergyMarkets_RealTimeMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_ForwardMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_FuturesMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_OptionsMarket;
    private javax.swing.JMenuItem jMenuItem_Markets_TransmissionRightsMarket;
    private javax.swing.JMenuItem jMenuItem_Participants_BilateralTrading_AlteratingOffers_Consumers;
    private javax.swing.JMenuItem jMenuItem_Participants_BilateralTrading_AlteratingOffers_Generators;
    private javax.swing.JMenuItem jMenuItem_Participants_BilateralTrading_AlteratingOffers_LargeConsumers;
    private javax.swing.JMenuItem jMenuItem_Participants_BilateralTrading_AlteratingOffers_Retailers;
    private javax.swing.JMenuItem jMenuItem_Participants_BilateralTrading_ContractNet;
    private javax.swing.JMenuItem jMenuItem_Participants_Generators;
    private javax.swing.JMenuItem jMenuItem_Participants_OTCTrading_Generators;
    private javax.swing.JMenuItem jMenuItem_Participants_OTCTrading_Retailers;
    private javax.swing.JMenuItem jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy1;
    private javax.swing.JMenuItem jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy2;
    private javax.swing.JMenuItem jMenuItem_Participants_PoolTrading_CaseStudies_CaseStudy3;
    private javax.swing.JMenuItem jMenuItem_Participants_PoolTrading_Generators;
    private javax.swing.JMenuItem jMenuItem_Participants_PoolTrading_Retailers;
    private javax.swing.JMenuItem jMenuItem_Participants_Retailers;
    private javax.swing.JMenuItem jMenuItem_Simulation_Bilateral_Pause;
    private javax.swing.JMenuItem jMenuItem_Simulation_Bilateral_Start;
    private javax.swing.JMenuItem jMenuItem_Simulation_Bilateral_Stop;
    private javax.swing.JMenuItem jMenuItem_Simulation_CaseStudy;
    private javax.swing.JMenuItem jMenuItem_Simulation_CaseStudyNoWind;
    private javax.swing.JMenuItem jMenuItem_Simulation_OTC;
    private javax.swing.JMenuItem jMenuItem_Simulation_Wholesale_Pause;
    private javax.swing.JMenuItem jMenuItem_Simulation_Wholesale_Start_LMP;
    private javax.swing.JMenuItem jMenuItem_Simulation_Wholesale_Start_SMP_Asymmetrical;
    private javax.swing.JMenuItem jMenuItem_Simulation_Wholesale_Start_SMP_Symmetrical;
    private javax.swing.JMenuItem jMenuItem_Simulation_Wholesale_Stop;
    private javax.swing.JMenu jMenu_Agents;
    private javax.swing.JMenu jMenu_Agents_Load;
    private javax.swing.JMenu jMenu_Agents_New;
    private javax.swing.JMenu jMenu_Exit;
    private javax.swing.JMenu jMenu_Markets;
    private javax.swing.JMenu jMenu_Markets_EnergyMarket;
    private javax.swing.JMenu jMenu_Markets_OverTheCounterContracts;
    private javax.swing.JMenuItem jMenu_Markets_OverTheCounterContracts_OTC;
    private javax.swing.JMenu jMenu_Participants;
    private javax.swing.JMenu jMenu_Participants_BilateralTrading;
    private javax.swing.JMenu jMenu_Participants_BilateralTrading_AlteratingOffers;
    private javax.swing.JMenu jMenu_Participants_OTCTrading;
    private javax.swing.JMenu jMenu_Participants_PoolTrading;
    private javax.swing.JMenu jMenu_Participants_PoolTrading_CaseStudies;
    private javax.swing.JMenu jMenu_Preferences;
    private javax.swing.JMenu jMenu_Simulation;
    private javax.swing.JMenu jMenu_Simulation_Bilateral;
    private javax.swing.JMenu jMenu_Simulation_Wholesale;
    private javax.swing.JMenu jMenu_Simulation_Wholesale_Start;
    private javax.swing.JMenu jMenu_Simulation_Wholesale_Start_SMP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPane_webtext;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea_webtext;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
