package scheduling;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import static java.lang.Integer.parseInt;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Collection;
//import java.lang.reflect.Array;
import javax.swing.JFrame;
//import java.util.ArrayList;
import java.util.List;
import static scheduling.AddGenerator.InfoSheet_h;
import static scheduling.AddGenerator.InfoSheet_t;
import static scheduling.AddGenerator.InfoSheet_w;

/**
 *
 * @author Af
 */


public class PreliminarInfo extends JFrame {
    
    private AddGenerator2 window;
    private ThermalInfo thermwindow;
    private HydroInfo hydrowindow;
    private ErrorMessage errormess;
    private WindCosts costswindow;
    public static List<String> provisString;
    public static List<String> DatatoUpdate;
    public static boolean UP;
    public static int ROW;

    
    /**
     * Creates new form PreliminarInfo
     */
    public PreliminarInfo() {
        
        initComponents();
        this.setTitle("Preliminar Info");
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        if (AddGenerator2.UP == true){
        updatefilling();  
        jComboBox1.setEditable(false);jComboBox1.setEnabled(false);
        jComboBox2.setEditable(false);jComboBox2.setEnabled(false);
        }
             
        if(AddGenerator.preWindData.length <= AddGenerator.InfoSheet_w.size() ){ 
            jComboBox1.removeItem("Wind Unit");     //Só deixa inserir o número de centrais que constem no excel importado
        }
        
        try{
        previousfilling();       
        }catch(NullPointerException | IndexOutOfBoundsException provisString){     
        }}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unit Data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setText("Production Technology:");

        jLabel2.setText("Fuel Type:");

        jLabel3.setText("Minimum Power:");

        jLabel4.setText("Maximum Power:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "Thermal Unit", "Hydro Unit", "Wind Unit" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "Coal", "Oil", "Natural Gas" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setText("MW");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("MW");

        jLabel7.setText("Unit Identification:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26))
        );

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

// CANCEL BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        window = new AddGenerator2(AddGenerator.prov_name);
        window.setVisible(true);
        try{
        PreliminarInfo.provisString.clear();
        }catch(NullPointerException r){
        }
        this.dispose();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    //FUEL Combo
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    
    //TECHNOLOGY Combo
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
if (jComboBox1.getSelectedIndex() == 1){      
        jComboBox2.setEnabled(true);
        jComboBox2.setSelectedIndex(0);
        if(AddGenerator2.UP == false){
            PredefinedThermal();
            jComboBox2.setSelectedItem(PreliminarInfo.provisString.get(2));
            jTextField1.setText(PreliminarInfo.provisString.get(3));
            jTextField2.setText(PreliminarInfo.provisString.get(4));
        }
}else{
          jComboBox2.setEnabled(false);              
          jComboBox2.setSelectedIndex(0);
              if(jComboBox1.getSelectedIndex() == 2){  //Não dá valores para Potencia da Hídrica
                jTextField1.setText(null); jTextField1.setEnabled(false);
                jTextField2.setText(null); jTextField2.setEnabled(false);
                    try{
                        PredefinedHydro();
                    }catch(IndexOutOfBoundsException e){}
              }
    }

if (jComboBox1.getSelectedIndex() != 2){   
    
    jTextField1.setEnabled(true);
    jTextField2.setEnabled(true);
    
}

if (jComboBox1.getSelectedIndex() == 3){   
    
    int index_unit = AddGenerator.InfoSheet_w.size();
    jTextField1.setText(String.valueOf(AddGenerator.preWindData[index_unit][0]));
    jTextField2.setText(String.valueOf(AddGenerator.preWindData[index_unit][1]));   
}


    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    //NEXT BUTTON
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int nID_test = 0;
        String ID_test = jTextField3.getText();
    
    for(int u = 0; u < AddGenerator.InfoSheet_t.size(); u++){
        if(AddGenerator.InfoSheet_t.get(u).ID.toString().equals(ID_test.toString())){
            nID_test++;
    }}
    for(int u = 0; u < AddGenerator.InfoSheet_h.size(); u++){
        if(AddGenerator.InfoSheet_h.get(u).ID.toString().equals(ID_test.toString())){
            nID_test++;
    }}
    for(int u = 0; u < AddGenerator.InfoSheet_w.size(); u++){
        if(AddGenerator.InfoSheet_w.get(u).ID.toString().equals(ID_test.toString())){
            nID_test++;
    }}
    
if(nID_test == 0){//Se nome for original        
    try{         
        if (jComboBox1.getSelectedIndex()==1){      //PARA AS TÉRMICAS
            if (jComboBox2.getSelectedIndex()!=0){  
               if (AddGenerator2.UP == true){
                        PreliminarInfo.provisString = new ArrayList<String>();
                        PreliminarInfo.provisString.add(0,jTextField3.getText());
                        PreliminarInfo.provisString.add(1,"Thermal");
                        PreliminarInfo.provisString.add(2,jComboBox2.getSelectedItem().toString());
                        PreliminarInfo.provisString.add(3,jTextField1.getText());
                        PreliminarInfo.provisString.add(4,jTextField2.getText());
                    }else{
                        PreliminarInfo.provisString.set(0,jTextField3.getText());
                        PreliminarInfo.provisString.set(1,"Thermal");
                        PreliminarInfo.provisString.set(2,jComboBox2.getSelectedItem().toString());
                        PreliminarInfo.provisString.set(3,jTextField1.getText());
                        PreliminarInfo.provisString.set(4,jTextField2.getText());}
               
                
                thermwindow = new ThermalInfo();    
                thermwindow.setVisible(true);       
                this.dispose();                    
}}

if (jComboBox1.getSelectedIndex()==2){ //PARA AS HÍDRICAS     
       if (AddGenerator2.UP == true){
                        provisString = new ArrayList<String>();
                        PreliminarInfo.provisString.add(0,jTextField3.getText());
                        PreliminarInfo.provisString.add(1,"Hydro");
                        PreliminarInfo.provisString.add(2,"Water");
        }else{
                        PreliminarInfo.provisString.set(0,jTextField3.getText());
                        PreliminarInfo.provisString.set(1,"Hydro");
                        PreliminarInfo.provisString.set(2,"Water");}
  
        
        hydrowindow = new HydroInfo();   
        hydrowindow.setVisible(true);     
        this.dispose();                   
}

if (jComboBox1.getSelectedIndex()==3){      //PARA AS EÓLICAS
        provisString = new ArrayList<String>();
        PreliminarInfo.provisString.add(0,jTextField3.getText());
        PreliminarInfo.provisString.add(1,"Wind");
        PreliminarInfo.provisString.add(2,"Wind");
        PreliminarInfo.provisString.add(3,jTextField1.getText());
        PreliminarInfo.provisString.add(4,jTextField2.getText());  
        
        costswindow = new WindCosts();         
        costswindow.setVisible(true);         
        this.dispose(); }


 
}catch(NumberFormatException numberFormatException){
        errormess = new ErrorMessage("Please Check Entered Data:","Too Long Number Inserted");
        errormess.setVisible(true);}
    }//GEN-LAST:event_jButton3ActionPerformed
    else{
        errormess = new ErrorMessage("Please Check Entered Data:","Unit ID Already in Use");
        errormess.setVisible(true);
    }
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    
    public void previousfilling (){
    
    jTextField3.setText(PreliminarInfo.provisString.get(0));
    jComboBox1.setSelectedItem(PreliminarInfo.provisString.get(1));
    jComboBox2.setSelectedItem(PreliminarInfo.provisString.get(2));       
    jTextField1.setText(PreliminarInfo.provisString.get(3));
    jTextField2.setText(PreliminarInfo.provisString.get(4));    
if (PreliminarInfo.provisString.get(1).equals("Thermal")){
    jComboBox1.setSelectedIndex(1);
    if (PreliminarInfo.provisString.get(2).equals("Coal")){
        jComboBox2.setSelectedIndex(1);}
    if (PreliminarInfo.provisString.get(2).equals("Oil")){
        jComboBox2.setSelectedIndex(2);}
    if (PreliminarInfo.provisString.get(2).equals("Natural Gas")){
        jComboBox2.setSelectedIndex(3);}
    }
if (PreliminarInfo.provisString.get(1).equals("Hydro")){
    jComboBox1.setSelectedIndex(2);
    }

if (PreliminarInfo.provisString.get(1).equals("Wind")){
    jComboBox1.setSelectedIndex(3);
}

//provisString.clear();
    }
    
    public void updatefilling(){

    jTextField3.setText(AddGenerator2.DatatoUpdate.get(0));      
    jTextField1.setText(AddGenerator2.DatatoUpdate.get(3));
    jTextField2.setText(AddGenerator2.DatatoUpdate.get(4));
    
if (AddGenerator2.DatatoUpdate.get(1).equals("Thermal")){
    jComboBox1.setSelectedIndex(1);
    if (AddGenerator2.DatatoUpdate.get(2).equals("Coal")){
       jComboBox2.setSelectedIndex(1);}
    if (AddGenerator2.DatatoUpdate.get(2).equals("Oil")){
        jComboBox2.setSelectedIndex(2);}
    if (AddGenerator2.DatatoUpdate.get(2).equals("Natural Gas")){
        jComboBox2.setSelectedIndex(3);}
    }
if (AddGenerator2.DatatoUpdate.get(1).equals("Hydro")){
    jComboBox1.setSelectedIndex(2);
    }

if (AddGenerator2.DatatoUpdate.get(1).equals("Wind")){
    jComboBox1.setSelectedIndex(3);
}
    }
    
    public void PredefinedHydro(){
    
    int index = AddGenerator.InfoSheet_h.size();
        
        this.provisString = new ArrayList<String>();
    
        PreliminarInfo.provisString.add(0,jTextField3.getText());
        PreliminarInfo.provisString.add(1,"Hydro");
        PreliminarInfo.provisString.add(2,"Water");
        
        PreliminarInfo.provisString.add(3,String.valueOf(AddGenerator.preOutputLimits[index][3])); //RU = PotenciaMaxima
        PreliminarInfo.provisString.add(4,String.valueOf(AddGenerator.preOutputLimits[index][3])); //RD = PotenciaMaxima
        PreliminarInfo.provisString.add(5,String.valueOf(AddGenerator.preHydroData[index][5])); //MinReserve
        PreliminarInfo.provisString.add(6,String.valueOf(AddGenerator.preHydroData[index][6])); //MaxReserve
        PreliminarInfo.provisString.add(7,String.valueOf(AddGenerator.preHydroData[index][2])); //InitReserve
        PreliminarInfo.provisString.add(8,String.valueOf(AddGenerator.preHydroData[index][0]));//MinDischarge
        PreliminarInfo.provisString.add(9,String.valueOf(AddGenerator.preHydroData[index][1]));//MaxDischarge
        PreliminarInfo.provisString.add(10,String.valueOf(AddGenerator.precosts[index][1]));//VariableCost
        //Selection
        //Cascade
        PreliminarInfo.provisString.add(11,String.valueOf(AddGenerator.preLinearization[index][0]));//p11
        PreliminarInfo.provisString.add(12,String.valueOf(AddGenerator.preLinearization[index][1]));//p12
        PreliminarInfo.provisString.add(13,String.valueOf(AddGenerator.preLinearization[index][2]));//p13
        PreliminarInfo.provisString.add(14,String.valueOf(AddGenerator.preLinearization[index][3]));//p14
        PreliminarInfo.provisString.add(15,String.valueOf(AddGenerator.preLinearization[index][4]));//Ul
        PreliminarInfo.provisString.add(16,String.valueOf(AddGenerator.preOutputLimits[index][0]));//P01
        PreliminarInfo.provisString.add(17,String.valueOf(AddGenerator.preOutputLimits[index][1]));//P02
        PreliminarInfo.provisString.add(18,String.valueOf(AddGenerator.preOutputLimits[index][2]));//P03
        PreliminarInfo.provisString.add(19,String.valueOf(AddGenerator.preOutputLimits[index][3]));//Pi
        PreliminarInfo.provisString.add(20,String.valueOf(AddGenerator.curves[index]));//Curves
        PreliminarInfo.provisString.add(21,String.valueOf(AddGenerator.preHydroData[index][7]));//Startupcost
        PreliminarInfo.provisString.add(22,String.valueOf(AddGenerator.preinflow[index]));//Inflow
        PreliminarInfo.provisString.add(23,String.valueOf(AddGenerator.preHydroData[index][3]));//LowLevel
        PreliminarInfo.provisString.add(24,String.valueOf(AddGenerator.preHydroData[index][4]));//UpperLevel
        PreliminarInfo.provisString.add(25,String.valueOf(AddGenerator.precosts[index][0]));//FixedCost
        PreliminarInfo.provisString.add(26,String.valueOf(0));//PrevProduction
        
    } 
    
    public void PredefinedThermal(){
    int index = AddGenerator.InfoSheet_t.size();
        
        this.provisString = new ArrayList<String>();
    
        PreliminarInfo.provisString.add(0,jTextField3.getText());
        PreliminarInfo.provisString.add(1,"Thermal");
        PreliminarInfo.provisString.add(2,AddGenerator.preThermalFuelindex[index]);
        PreliminarInfo.provisString.add(3,String.valueOf(AddGenerator.preThermalData[index][0])); //Potencia Minima
        PreliminarInfo.provisString.add(4,String.valueOf(AddGenerator.preThermalData[index][1])); //Potencia Maxima
        
        PreliminarInfo.provisString.add(5,String.valueOf(AddGenerator.preThermalData[index][2])); //RU
        PreliminarInfo.provisString.add(6,String.valueOf(AddGenerator.preThermalData[index][3])); //RD
        PreliminarInfo.provisString.add(7,String.valueOf(AddGenerator.preThermalData[index][4])); //MinON
        PreliminarInfo.provisString.add(8,String.valueOf(AddGenerator.preThermalData[index][5]));//MinOFF
        PreliminarInfo.provisString.add(9,"PrevProd");//PrevProd
        PreliminarInfo.provisString.add(10,String.valueOf(AddGenerator.preThermalcosts[index][0]));//FCost
        PreliminarInfo.provisString.add(11,String.valueOf(AddGenerator.preThermalcosts[index][1]));//VCost        
        //Selection
        PreliminarInfo.provisString.add(12,String.valueOf(AddGenerator.preThermalData[index][6]));//StartUpcost
        PreliminarInfo.provisString.add(13,String.valueOf(AddGenerator.preThermalData[index][8]));//ShutDowncost
        PreliminarInfo.provisString.add(14,String.valueOf(AddGenerator.preThermalData[index][9]));//initStatus
        PreliminarInfo.provisString.add(15,String.valueOf(AddGenerator.preThermalFuelCons[index][0])); //Fuel Consuption Fixed
        PreliminarInfo.provisString.add(16,String.valueOf(AddGenerator.preThermalFuelCons[index][1])); //Fuel Consuption Variable
        PreliminarInfo.provisString.add(17,String.valueOf(AddGenerator.preThermalEMISSIONS[index][0])); //Emissions CO2
        PreliminarInfo.provisString.add(18,String.valueOf(AddGenerator.preThermalEMISSIONS[index][1])); //Emissions NO2
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreliminarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreliminarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreliminarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreliminarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreliminarInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
